ALTER TABLE products ADD COLUMN set_of_2_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN set_of_2_price DECIMAL(10,2) NULL;
ALTER TABLE cart_items ADD COLUMN pack_size INT NOT NULL DEFAULT 1;
ALTER TABLE order_items ADD COLUMN pack_size INT NOT NULL DEFAULT 1;
